import { Injectable, Logger } from '@nestjs/common';
import { DatabaseService } from '../database/database.service';
import { Octokit } from '@octokit/rest';
import OpenAI from 'openai';

@Injectable()
export class ActionsService {
  private readonly logger = new Logger(ActionsService.name);
  private openai: OpenAI;

  constructor(private readonly db: DatabaseService) {
    this.openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  }

  async createGitHubIssue(userId: string, repoId: string, title: string, body: string) {
    const integration = await this.db.integration.findFirst({
      where: { userId, provider: 'github' }
    });
    if (!integration) throw new Error('No GitHub integration found');

    const repo = await this.db.repository.findUnique({ where: { id: repoId } });
    if (!repo) throw new Error('Repository not found');

    const octokit = new Octokit({ auth: integration.accessToken });
    // Expect repo url to be like https://github.com/owner/repo
    const parts = repo.url.split('/');
    const repoName = parts.pop();
    const ownerName = parts.pop();

    if (!repoName || !ownerName) throw new Error('Invalid repository URL');

    const response = await octokit.issues.create({
      owner: ownerName,
      repo: repoName,
      title: title,
      body: body + '\n\n---\n*Generated by DevMetrics AI*'
    });

    return { success: true, url: response.data.html_url };
  }

  async draftPrSummary(pullRequestId: string) {
    const pr = await this.db.pullRequest.findUnique({ where: { id: pullRequestId }, include: { commits: true } });
    if (!pr) throw new Error('PR not found');

    const commitMessages = pr.commits.map(c => c.message).join('\n');
    const prompt = `You are an AI code reviewer. Based on the following commit messages for PR "${pr.title}", write a concise PR summary description (2-3 paragraphs max) that highlights the what, why, and how of the changes.\n\nCommits:\n${commitMessages}`;

    try {
      const response = await this.openai.chat.completions.create({
        model: 'gpt-4o',
        messages: [{ role: 'user', content: prompt }]
      });
      return { success: true, summary: response.choices[0].message.content };
    } catch (error) {
      this.logger.error('OpenAI draft PR summary error', error);
      return { success: false, summary: 'AI service unavailable to draft summary. Please manually review the commits.' };
    }
  }

  async suggestRefactor(insightId: string) {
    const insight = await this.db.insight.findUnique({ where: { id: insightId } });
    if (!insight) throw new Error('Insight not found');

    const prompt = `Based on this engineering insight:\n\nTitle: ${insight.title}\nDescription: ${insight.description}\nRecommendation: ${insight.recommendation}\n\nGenerate a concrete, step-by-step refactoring plan to address this issue.`;

    try {
      const response = await this.openai.chat.completions.create({
        model: 'gpt-4o',
        messages: [{ role: 'user', content: prompt }]
      });
      return { success: true, suggestion: response.choices[0].message.content };
    } catch (error) {
      this.logger.error('OpenAI refactor suggest error', error);
      return { success: false, suggestion: 'AI service unavailable. Please follow standard refactoring guidelines.' };
    }
  }
}
