import { Injectable, Logger } from '@nestjs/common';
import { DatabaseService } from '../database/database.service';
import { Octokit } from '@octokit/rest';
import { GoogleGenAI } from '@google/genai';

@Injectable()
export class ActionsService {
  private readonly logger = new Logger(ActionsService.name);
  private ai: GoogleGenAI;

  constructor(private readonly db: DatabaseService) {
    this.logger.log('Initializing Google Gemini AI client in ActionsService');
    try {
      this.ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
      this.logger.log('Google Gemini AI client initialized successfully');
    } catch (error) {
      this.logger.error('Failed to initialize Google Gemini AI client', error);
    }
  }

  async createGitHubIssue(userId: string, repoId: string, title: string, body: string) {
    const integration = await this.db.integration.findFirst({
      where: { userId, provider: 'github' }
    });
    if (!integration) throw new Error('No GitHub integration found');

    const repo = await this.db.repository.findUnique({ where: { id: repoId } });
    if (!repo) throw new Error('Repository not found');

    const octokit = new Octokit({ auth: integration.accessToken });
    // Expect repo url to be like https://github.com/owner/repo
    const parts = repo.url.split('/');
    const repoName = parts.pop();
    const ownerName = parts.pop();

    if (!repoName || !ownerName) throw new Error('Invalid repository URL');

    const response = await octokit.issues.create({
      owner: ownerName,
      repo: repoName,
      title: title,
      body: body + '\n\n---\n*Generated by DevMetrics AI*'
    });

    return { success: true, url: response.data.html_url };
  }

  async draftPrSummary(pullRequestId: string) {
    const pr = await this.db.pullRequest.findUnique({ where: { id: pullRequestId }, include: { commits: true } });
    if (!pr) throw new Error('PR not found');

    const commitMessages = pr.commits.map(c => c.message).join('\n');
    const prompt = `You are an AI code reviewer. Based on the following commit messages for PR "${pr.title}", write a concise PR summary description (2-3 paragraphs max) that highlights the what, why, and how of the changes.\n\nCommits:\n${commitMessages}`;

    try {
      this.logger.log(`Requesting PR summary from Gemini for PR: ${pr.title}`);
      const response = await this.ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt
      });
      this.logger.log(`Received PR summary response from Gemini for PR: ${pr.title}`);
      return { success: true, summary: response.text };
    } catch (error: any) {
      this.logger.error(`Gemini draft PR summary error: ${error.message || String(error)}`, error);
      return { success: false, summary: 'AI service unavailable to draft summary. Please manually review the commits.' };
    }
  }

  async suggestRefactor(insightId: string) {
    const insight = await this.db.insight.findUnique({ where: { id: insightId } });
    if (!insight) throw new Error('Insight not found');

    const prompt = `Based on this engineering insight:\n\nTitle: ${insight.title}\nDescription: ${insight.description}\nRecommendation: ${insight.recommendation}\n\nGenerate a concrete, step-by-step refactoring plan to address this issue.`;

    try {
      this.logger.log(`Requesting refactor suggestion from Gemini for insight: ${insight.title}`);
      const response = await this.ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt
      });
      this.logger.log(`Received refactor suggestion response from Gemini for insight: ${insight.title}`);
      return { success: true, suggestion: response.text };
    } catch (error: any) {
      this.logger.error(`Gemini refactor suggest error: ${error.message || String(error)}`, error);
      return { success: false, suggestion: 'AI service unavailable. Please follow standard refactoring guidelines.' };
    }
  }
}
